[tool.poetry]
name = "fastapi_learnings"
version = "0.1.0"
description = "fast Api things"
authors = ["Jyoti"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"
python-dotenv = "^1.0.0"
fastapi = "~0.115"
uvicorn = "^0.34.0"
